### ISSUE TITLE
Wrong comparison operator in FactoryCreator.java?

### ISSUE THREAD

**Issue by oscar-v0** [ACH87/Pokemon_Battle_Simulator#1]
https://github.com/ACH87/Pokemon_Battle_Simulator/blob/d9cc9ae0ba69efd3d756d36aa6302cefe5e473e4/src/Factories/FactoryCreator.java#L26
https://github.com/ACH87/Pokemon_Battle_Simulator/blob/d9cc9ae0ba69efd3d756d36aa6302cefe5e473e4/src/Factories/FactoryCreator.java#L44

I assume you meant `equals(name)` instead of `==`

You've been using too much JS I see

**Comment by ACH87** [comment]
yes, yes i was
